/**:
  ros__parameters:
    control_hz: 20.0 # handle_hold rate   50ms 0.05sec
    trajectory_dt: 0.05
    close_step: 0.03 # hold : 0.03
    contact_threshold: 30.0 # // org : 10.0    //pinch : 3.0
    thumb_contact_ratio: 2.0 # thumb contact = other finger threshold 2x
    un_use_finger: [9] # thumb: 0, index: 1, middle: 2, ring: 3, little: 4     비워 놓는건 안됨?

    # tactile_sensor
    x_center: 0.5 # // top down    : 70 almost ignore    best : 60
    y_center: 0.2 # // dead-zone(0~1)    : org 0.35
    min_force_correction: 10.0
    cost_thres: 0.1
    ##   double min_force_for_correction_{10.0};
    ## double cost_threshold_{0.1};

    # hold
    reactive_force: 1.2

    # optimize
    feedback_max_delta: 0.01 # feedback max step
    regrasp_force: 3.0 # 재그립 완료 기준 = 평소 threshold의 1.5배       무거 3.0 과일 1.5
